services:
  postgres:
    image: postgres:18-alpine
    container_name: facets-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stephanofer
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: facets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stephanofer -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: